### ISSUE TITLE
Inclusive / Non-Inclusive Code Comment

### ISSUE THREAD

**Issue by jaruba** [ThaUnknown/nzb-file#1]
Hi, can you explain what this code comment means?
https://github.com/ThaUnknown/nzb-file/blob/bc0bf8ec0b9f1ccf0f5056562598a3fca3dbc413/src/index.ts#L74

Thanks 🙂

**Comment by ThaUnknown** [comment]
inclusive means the position you specify is included in the data or not, W3C aka WWW Consortium's API's usually specify data ends as non-inclusive, where as NodeJS APIs are usually end inclusive, since this file object replicates W3C's `File` object, the `end` positions are non-inclusive, but this means that if you then take this data and put it into a nodejs api your data sizes will be miss-matched by 1 byte

**Comment by jaruba** [comment]
that's what i imagined, 1 byte offset
hi from Stremio btw 👋 
i think the two of us might be pushing efforts towards the same direction right now

**Comment by jaruba** [comment]
you are also, weirdly enough, the only other person i've seen with a similar number of followers that does not follow anybody 🙂

**Comment by ThaUnknown** [comment]
no, I highly doubt we are, I'm interested in improving the state of decentralized media, from what I can tell you're interested in leeching of off other platforms which provide content for free

it's called "really not giving a fuck", I'm using github as a git service, not a social media platform

**Comment by jaruba** [comment]
i respect your POV, even though I do no agree with it
i do recognize your efforts and your skill, will leave it at that
